name: Build AboutMe App

on:
  push:
    paths:
      - '3-aboutme/about_me.py'
      - '3-aboutme/requirements.txt'
      - '.github/workflows/build-aboutme.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows-exe:
    name: Build Windows EXE
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install build dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path '3-aboutme/requirements.txt') {
            python -m pip install -r 3-aboutme/requirements.txt
          } else {
            python -m pip install pyinstaller requests psutil wmi pywin32
          }

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          Set-Location 3-aboutme
          $icon = Test-Path 'icon.ico'
          if ($icon) {
            pyinstaller --noconfirm --clean --onefile --name AboutMe_ComputerInfo --icon icon.ico about_me.py
          } else {
            pyinstaller --noconfirm --clean --onefile --name AboutMe_ComputerInfo about_me.py
          }

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: AboutMe_ComputerInfo-exe
          path: 3-aboutme/dist/AboutMe_ComputerInfo.exe
          if-no-files-found: error

      - name: Copy EXE to docs download folder
        if: ${{ always() }}
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path docs/assets | Out-Null
          New-Item -ItemType Directory -Force -Path docs/assets/download | Out-Null
          Copy-Item 3-aboutme/dist/AboutMe_ComputerInfo.exe docs/assets/download/AboutMe_ComputerInfo.exe -Force

      - name: Commit updated EXE to repository
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/assets/download/AboutMe_ComputerInfo.exe
          if (git diff --cached --quiet) {
            Write-Output "No changes to commit."
          } else {
            git commit -m "chore(aboutme): update compiled AboutMe_ComputerInfo.exe"
            git push
          }


