name: Handle Computer Data

on:
  repository_dispatch:
    types: [computer-data]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (dry run)'
        required: false
        default: false
        type: boolean

jobs:
  handle-computer-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests pyyaml flask
        sudo apt-get update
        sudo apt-get install -y jq
    
    - name: Create backup directory
      run: |
        mkdir -p 1-website/assets/computer_info_data_backup
        echo "Created backup directory"
    
    - name: Process computer data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
      run: |
        set -e  # Exit on any error
        
        echo "Processing computer data (test mode: $TEST_MODE)..."
        if [ "$TEST_MODE" = "true" ]; then
          echo "TEST MODE: Would process computer data here"
          echo "In test mode, no actual data processing occurs"
          echo "✅ Test mode completed successfully"
        else
          echo "Processing computer data using server..."
          
          # Run the server to process the computer data
          cd 4-server
          python server.py
          
          echo "✅ Computer data processing completed successfully"
        fi
    
    - name: Verify processing completed
      if: github.event.inputs.test_mode != 'true'
      run: |
        echo "Computer data processing completed by server"
        echo "Server handles all data updates and commits automatically"