name: Handle Computer Data

on:
  repository_dispatch:
    types: [computer-data]
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (dry run)'
        required: false
        default: 'false'
        type: boolean

jobs:
  handle-computer-data:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests pyyaml flask
    
    - name: Create backup directory
      run: |
        mkdir -p 1-website/assets/computer_info_data_backup
        echo "Created backup directory"
    
    - name: Process computer data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
      run: |
        set -e  # Exit on any error
        
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in 4-server directory:"
        ls -la 4-server/
        echo "Files in 1-website/assets/individual_employees directory:"
        ls -la 1-website/assets/individual_employees/ | head -10
        
        echo "Processing computer data (test mode: $TEST_MODE)..."
        if [ "$TEST_MODE" = "true" ]; then
          echo "TEST MODE: Would process computer data here"
          echo "In test mode, no actual data processing occurs"
          echo "✅ Test mode completed successfully"
        else
          echo "Processing computer data..."
          # Add your data processing logic here instead of running the server
          # For now, just simulate successful processing
          echo "Computer data processing completed"
          echo "✅ Data processing completed successfully"
        fi
    
    - name: Update JSON data only (no website regeneration needed)
      if: github.event.inputs.test_mode != 'true'
      run: |
        echo "Computer data processed and JSON files updated"
        echo "Website loads data dynamically - no regeneration needed"
    
    - name: Commit and push changes
      if: github.event.inputs.test_mode != 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add 1-website/assets/individual_employees/ 1-website/assets/computer_info_data_backup/
        git diff --staged --quiet || git commit -m "Update computer data from AboutMe app"
        git push