name: Handle Computer Data Simple

on:
  repository_dispatch:
    types: [computer-data]

jobs:
  handle-computer-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests pyyaml flask
    
    - name: Create directories
      run: |
        mkdir -p 1-website/assets/computer_info_data_backup
        echo "Directories created"
    
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Python version:"
        python --version
        echo "GitHub event data:"
        cat $GITHUB_EVENT_PATH | head -20
    
    - name: Test server import
      run: |
        echo "Testing server.py import..."
        python -c "import sys; sys.path.append('4-server'); import server; print('Server import successful')"
