name: Manual Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test step
      run: |
        echo "Manual test workflow is working"
        echo "Current directory: $(pwd)"
        ls -la
        echo "Python version:"
        python --version
