name: Regenerate Website

on:
  push:
    paths:
      - 'assets/computer_data/**'
      - 'assets/employees_data.json'
  workflow_dispatch:

jobs:
  regenerate-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install requests pyyaml
    
    - name: Regenerate website with computer data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "🔄 Regenerating website with updated data..."
        
        # Run the website regeneration script
        python .github/scripts/regenerate_website.py
        
        # Check if HTML was generated successfully
        if [ -f "index.html" ]; then
          echo "✅ Website regenerated successfully"
        else
          echo "❌ Website regeneration failed"
          exit 1
        fi
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html assets/
        git diff --staged --quiet || git commit -m "Regenerate website with updated data"
        git push
